# Site settings
title: Life
email: brett.grobarz@gmail.com
description: "The Life and Times of Brett J. Grobarz"
baseurl: ""
url: "brettgrobarz.github.io"
twitter_username: brettgrobarz
github_username:  brettgrobarz

# Build settings
markdown: kramdown
permalink: pretty
